export const GET_TUTORS_BEGIN =   'GET_TUTORS_BEGIN';
export const GET_TUTORS_SUCCESS = 'GET_TUTORS_SUCCESS';

export const GET_TUTOR_BEGIN =   'GET_TUTOR_BEGIN';
export const GET_TUTOR_SUCCESS = 'GET_TUTOR_SUCCESS';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN =   'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR =   'LOGIN_USER_ERROR';

export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const ADD_TUTOR_IMAGE = 'ADD_TUTOR_IMAGE';
export const LOGOUT_USER = 'LOGOUT_USER';