export const GET_TUTORS_BEGIN =   'GET_TUTORS_BEGIN';
export const GET_TUTORS_SUCCESS = 'GET_TUTORS_SUCCESS';

export const GET_TUTOR_BEGIN =   'GET_TUTOR_BEGIN';
export const GET_TUTOR_SUCCESS = 'GET_TUTOR_SUCCESS';

export const CREATE_TUTOR_BEGIN =   'CREATE_TUTOR_BEGIN';
export const CREATE_TUTOR_SUCCESS = 'CREATE_TUTOR_SUCCESS';
export const CREATE_TUTOR_ERROR =   'CREATE_TUTOR_ERROR';
